dist: trusty
sudo: required

env:
  global:
    - CXX=g++-4.8
    - ds_cockroach=postgresql://root@localhost:26257?sslmode=disable
    - ds_dbName=deepstream
    - ds_tableName=deepstream_storage
    - ds_keyType=text
    - ds_valueType=text
    - ds_splitter=/

language: node_js

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "7"

before_install:
  - sudo apt-get update -qq
  - curl -o cockroach.tgz -L https://binaries.cockroachdb.com/cockroach-latest.linux-amd64.tgz
  - tar xfz ./cockroach.tgz
  - sudo cp cockroach-latest.linux-amd64/cockroach /usr/local/bin/.
  - sudo chmod 755 /usr/local/bin/cockroach

script:
  - /usr/local/bin/cockroach start
  - npm run test
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/package.sh
  - chmod 555 package.sh
  - ./package.sh

deploy:
  - provider: s3
    access_key_id:
      secure: "CY/dcxTFNWaMTkEpTLXCYUVHAKqy5+w/bGIEBLopDLAgsieHoNkHdi83IlQiNXMbYfyjixPPb5y2JENT9gllAkAZv8TLgGgM5z5Lh5LrnXel72rzlqQfxZevXQ6DU5b6aOzPTgjcjwD401tLlajha5DcNbvZy5dMvi59E6HCGdM="
    secret_access_key:
      secure: "Y7GFu19JEXqVf60tTD1I5UjOheG3Tzma8fat0b53A0g50BVCUf68SNBVUKfRSxo1Ja4M81j08tz9924uGC2FVE6iP4G8AwF60aezgfxbaI9ItfFbustSEQJzvetf9JE98GQXEZFptLUSGhsdWJe6P4SgLq1fssmoAQrompNiT9E="
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "R6SZFsJIBLQl76uzldbQI12x+EYZKseXNVNI7rI43N+6KJLxWTsDH7tuiTImrdMsJmpLhCACHHzA0ZLztFxVpEKduNjdMZGsTEV0JB8zOGbsOfvaOss/l3IsWlhYqSlHe8jnHjZnC+nBEwCdivVamx+zLBw8qVVaG1Lba0Z8DzU="
    file_glob: true
    file:
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/test.sh
  - chmod 555 test.sh
  - ./test.sh

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"