plugins:
  storage:
    name: deepstream.io-storage-cockroachdb
    options:
      ds_host: 'postgresql://root@localhost:26257?sslmode=disable'
      ds_databaseName: 'deepstream'
      ds_tableName: 'deepstream_storage'
      ds_keyType: 'text'
      ds_valueType: 'text'
      ds_splitter: '/'